version: "3.5"

x-logging: &default-logging
  options:
    max-size: "1m"
    max-file: "5"
  driver: json-file

services:
  kafka:
    image: kafka
    volumes:
      - ./data/kafka/logs:/data/kafka
      - ./config/server.properties:/opt/kafka/default/config/server.properties:ro
      - ./data/zookeeper/logs:/data/zookeeper
      - ./config/zookeeper.properties:/opt/kafka/default/config/zookeeper.properties:ro
      - ./data/logs:/opt/kafka/default/logs
    ports:
      - 9092:9092
      - 2181:2181
    logging: *default-logging
    restart: always
